### ISSUE TITLE
Path.join

### ISSUE THREAD

**Issue by NoureldeanSaed** [FACG4/week4-auto-translator#18]
https://github.com/FACG4/week4-auto-translator/blob/ebc52d17b3c029105dd131c166e38de8dd3edfbe/src/handler.js#L22-L26

Ever heard of ```path.join```? Look it up.

**Comment by amusameh** [comment]
We had it all wrong , thanks for pointing this out :+1:

**Comment by NoureldeanSaed** [comment]
You can close the issue @amusameh
